### PR TITLE
Remove region validation function

### LINKED ISSUE #65: Creating a project using "aws-us-east-1" region fails
Hi and thanks for developing this!

We are facing an issue creating a new project using the "aws-us-east-1" region. From the [docs](https://neon.tech/docs/introduction/regions) it seems this region is supported, and trying to create a project using the api works, but terraform outputs `region aws-us-east-1 is not supported yet: https://neon.tech/docs/introduction/regions/`.
I think it's related to [this](https://github.com/kislerdm/terraform-provider-neon/blob/master/internal/provider/helper.go#L46) check.

Thank you!

### Terraform Version
Terraform v1.6.6

### Provider Version
provider registry.terraform.io/kislerdm/neon v0.3.1

### Affected Resource(s)
- neon_project

### Terraform Configuration Files
```hcl
resource "neon_project" "this" {
    name      = "this"
    region_id = "aws-us-east-1"
}
```

### Steps to Reproduce
1. `terraform apply`

### PR DESCRIPTION
**Pull request by rshulman-trigo**
Hi! 

Not sure if you wanted to remove the validation all together and just let the api fail, or just add the new supported regions. For now i've added the missing regions to the validation.

Thanks!

Closes #65

### CODE REVIEW

**Comment by kislerdm** [comment]
@rshulman-trigo Hey! Thank you for your PR! 

It's a great assumption: I was going to suggest removing unnecessary validation. This unnecessary complexity brings more harm than good 🙂

**Review by kislerdm — COMMENTED** [review]
Hey @rshulman-trigo! Thank you for your contribution! I'd suggest to remove validation as you suggested. Would you mind implementing it? Thanks!

**Comment by rshulman-trigo** [comment]
yes - I removed the function. Hope this is good?

**Review by kislerdm — APPROVED** [review]
Great! Thank you @rshulman-trigo!

**Pull request merged**
